package org.raflab.studsluzba.services;
import lombok.RequiredArgsConstructor;import org.raflab.studsluzba.model.*;import org.raflab.studsluzba.model.finance.LedgerEntry;import org.raflab.studsluzba.model.ispiti.PrijavaIspita;import org.raflab.studsluzba.model.security.Permission;import org.raflab.studsluzba.repositories.*;import org.raflab.studsluzba.repositories.finance.LedgerEntryRepository;import org.springframework.stereotype.Service;
import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.util.*;
@Service @RequiredArgsConstructor
public class ReportingService{
 private final StudentIndeksRepository indeksRepo;private final LedgerEntryRepository ledgerRepo;private final IspitQueryRepository examRepo;private final PermissionService permissions;
 public byte[] activeStudents(){permissions.require(Permission.REPORT_EXPORT);StringBuilder s=new StringBuilder("indeks_id,program,godina,broj,status\n");for(StudentIndeks i:indeksRepo.findAll())if(i.getStatus()==StudentStatus.AKTIVAN||i.isAktivan())s.append(i.getId()).append(',').append(csv(i.getStudProgramOznaka())).append(',').append(i.getGodina()).append(',').append(i.getBroj()).append(",AKTIVAN\n");return bytes(s);}
 public byte[] debts(){permissions.require(Permission.REPORT_EXPORT);StringBuilder s=new StringBuilder("indeks_id,dug_eur,preplata_eur\n");for(StudentIndeks i:indeksRepo.findAll()){BigDecimal b=ledgerRepo.findByStudentIndeksIdOrderByCreatedAtAsc(i.getId()).stream().map(LedgerEntry::getAmountEur).reduce(BigDecimal.ZERO,BigDecimal::add);s.append(i.getId()).append(',').append(b.max(BigDecimal.ZERO)).append(',').append(b.min(BigDecimal.ZERO).abs()).append('\n');}return bytes(s);}
 public byte[] passRates(){permissions.require(Permission.REPORT_EXPORT);Map<Long,int[]>m=new TreeMap<>();for(PrijavaIspita p:examRepo.findAll()){if(Boolean.TRUE.equals(p.getPonisteno())||!p.isDaLiJeIzasao()||p.getIspit()==null)continue;int[]v=m.computeIfAbsent(p.getIspit().getId(),x->new int[2]);v[0]++;if(p.getOcena()>=6)v[1]++;}StringBuilder s=new StringBuilder("ispit_id,izasli,polozili,prolaznost\n");m.forEach((id,v)->s.append(id).append(',').append(v[0]).append(',').append(v[1]).append(',').append(v[0]==0?0:(100.0*v[1]/v[0])).append('\n'));return bytes(s);}
 private byte[]bytes(StringBuilder s){return s.toString().getBytes(StandardCharsets.UTF_8);}private String csv(String v){return v==null?"":("\""+v.replace("\"","\"\"")+"\"");}
}
