package org.raflab.studsluzba.model.security;
public enum Permission {
    FINANCE_READ, FINANCE_WRITE, AUDIT_READ, SETTINGS_READ, SETTINGS_WRITE,
    ENROLLMENT_WRITE, STUDENT_STATUS_WRITE, DOCUMENT_DECIDE, REPORT_EXPORT, SECURITY_ADMIN,
    LEADS_READ, LEADS_EXPORT
}
